name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: source docker/build_docker.sh
    - name: Push the Docker image to dockerhub
      env:
       DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
       docker login -u arumatik -p ${{ DOCKERHUB_TOKEN }}
       docker push arumatik/rosbase
